version: '3.8'

services:
  dev-php:
    build:
      context: .
      dockerfile: ./docker/development/dev-php/Dockerfile
    tty: true
    stdin_open: true
    # env_file: .env
    volumes:
      - "./backend:/var/www"
  
  symfony:
    # image: php:8.4-cli-alpine
    build:
      context: .
      dockerfile: ./docker/development/dev-php/Dockerfile
    volumes:
      - "./backend:/var/www"
    ports:
      - "8000:8000"
    command: symfony server:start --allow-all-ip

#   vue3:
#     image: node:lts
#     working_dir: /var/www/html/app/
#     entrypoint: /bin/bash
#     ports:
#       - "8001:8001"
#     volumes:
#       - ./frontend/:/var/www/html/app
#     tty: true

# networks:
#   app-network:
#     driver: bridge
